// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, server;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    return res.send('Hello World');
  });

  server = app.listen(3000, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log("Example coffee app at http://" + host + ":" + port);
  });

}).call(this);

//# sourceMappingURL=app.js.map
