// Generated by CoffeeScript 1.10.0
(function() {
  var cb0, cb1, cb2, express, router, title;

  express = require('express');

  router = express.Router();

  title = 'Express';

  router.all('/', function(req, res, next) {
    title += ' after all';
    return next();
  });

  router.get('/', function(req, res) {
    return res.render('index', {
      title: title
    });
  });

  router.get('/about', function(req, res) {
    return res.render('index', {
      title: 'about'
    });
  });

  cb0 = function(res, req, next) {
    console.log('cb0 executed...');
    return next();
  };

  cb1 = function(res, req, next) {
    console.log('cb1 executed...');
    return next();
  };

  cb2 = function(res, req, next) {
    console.log('cb2 executed...');
    return next();
  };

  router.get('/route-handlers', [cb0, cb1, cb2], function(req, res) {
    return res.render('index', {
      title: 'route handlers'
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
