// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.send('respond with a resource');
  });

  router.get('/mine', function(req, res) {
    return res.render('mine', {
      name: 'Yang xu',
      age: 29
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=user.js.map
